//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerPayment
    {
        public int Id { get; set; }
        public int AnswerId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Time { get; set; }
        public int PaymentTypeId { get; set; }
        public int Amount { get; set; }
        public string Token { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual User User { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
