//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerRating
    {
        public int Id { get; set; }
        public string AspNetUserId { get; set; }
        public int AnswerId { get; set; }
        public System.DateTime OriginDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public bool IsDeleted { get; set; }
        public int Rating { get; set; }
    
         public virtual Answer Answer { get; set; }
         public virtual AspNetUser AspNetUser { get; set; }
    }
}
