//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQ.Model
{
    using System;

    public partial class QuestionView
    {    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int QuestionId { get; set; }
        public DateTime EventTime { get; set; }
        public string IpAddress { get; set; }
    
        public virtual User User { get; set; }
        public virtual Question Question { get; set; }
    }
}
