//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string School { get; set; }
        public string Concentration { get; set; }
        public string SecondaryConcentration { get; set; }
        public string DegreeType { get; set; }
        public Nullable<int> GraduationYear { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
